name: Joel Klassen

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

repository: Joel-Klassen/Joel-Klassen.github.io

# Site settings
title: Your awesome title
email: joeldavidklassen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal homepage of Dr. Joel Klassen. 
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://localhost:4000'
#url: 'http://yourdomain.com' # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: Joel-Klassen
